# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Generate config YAML file
description: Generate Partner Center CLI config YAML file
inputs:
  file:
    description: The configuration file to convert
    required: true
    default: config.json.tmpl
  outputFile:
    description: The config YAML output path
    required: false
    default: config.yml
  workingDirectory:
    description: The current working directory
    default: '.'
runs:
  using: composite
  steps:
    - name:  Generate Partner Center CLI configuration file
      shell: bash
      working-directory: ${{ inputs.WorkingDirectory }}
      run: |
        python $GITHUB_ACTION_PATH/generatePCYaml.py ${{ inputs.file }} ${{ inputs.outputFile }}
