# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Azure Partner Center CLI
description: Run Azure Partner Center CLI commands
inputs:
  offerType:
    description: The offer type to run command on
    required: true
  command:
    description: The CLI command to run
    required: true
  arguments:
    description: The arguments for the command
    default: ''
  version:
    description: The version of the Azure Partner Center CLI to install, example >=0.0.40
    default: ''
  workingDirectory:
    description: The working directory
    default: '.'
outputs:
  response:
    description: Response from command
    value: ${{ steps.run-command.outputs.response }}
runs:
  using: composite
  steps:
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft' 
        java-version: '17'
    - name: Install CLI
      id: install-cli
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        $folder_name = "$GITHUB_ACTION_PATH/az-partner-center-cli"
        mkdir -p $folder_name
        git clone https://github.com/microsoft/az-partner-center-cli.git $folder_name
        cd $folder_name
        git checkout alexkoller/testCLIHangIssue 
        pip install pip==21.0.1 >/dev/null 2>&1 && \
        pip install -e . && \
        pip install --upgrade pyOpenSSL >/dev/null 2>&1 || exit 1
    - name: Run command
      id: run-command
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        azpc ${{ inputs.offerType }} ${{ inputs.command }} ${{ inputs.arguments }}
